name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: npm install, build and test
      run: |
        npm install
        npm run build --if-present
        
    - name: Simple FTP deploy
      uses: kevinpainchaud/simple-ftp-deploy-action@v1.1.0
      with:
        ftp_host: sftp://skymaster.dreamhost.com/
        ftp_username: stefanoperfili
        ftp_password: ${{ secrets.FTP_PASSWORD }}
        local_source_dir: dist/
        dist_target_dir: home/stefanoperfili/public/august/
        delete: true
        disable_ssl_certificate_verification: true
